apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoops-ui
  namespace: whoops
spec:
  selector:
    matchLabels:
      app: whoops-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: whoops-ui
    spec:
      containers:
        - name: whoops-ui
          image: ghcr.io/kryoseu/whoops-ui:v1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: WHOOP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: whoops-creds
                  key: CLIENT_ID
            - name: WHOOP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: whoops-creds
                  key: CLIENT_SECRET
            - name: WHOOP_REDIRECT_URI
              value: "https://whoops-ui.kryoseu.com/api/whoop/callback"
            - name: WHOOPS_URL
              value: "https://whoops.kryoseu.com"
