apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-home-apps
provisioner: nfs-home-apps.k8s.io
parameters:
  readOnly: "false"
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-plex
provisioner: nfs-plex.k8s.io
parameters:
  readOnly: "false"
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Retain
