apiVersion: v1
kind: Service
metadata:
  name: paperless-server
spec:
  selector:
    app: paperless-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-server
  namespace: paperless-ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-server
  template:
    metadata:
      labels:
        app: paperless-server
    spec:
      containers:
        - name: paperless-ngx
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.7
          ports:
            - containerPort: 8000
          env:
            - name: PAPERLESS_FILENAME_FORMAT
              value: "{{ created_year }}/{{ created_month }}/{{ correspondent }}/{{ title }}"
            - name: PAPERLESS_URL
              value: https://paperless.kryoseu.com
            - name: PAPERLESS_ALLOWED_HOSTS
              value: paperless.kryoseu.com
            - name: PAPERLESS_CORS_ALLOWED_HOSTS
              value: https://paperless.kryoseu.com
            - name: PAPERLESS_OCR_LANGUAGE
              value: eng
            - name: PAPERLESS_OCR_LANGUAGES
              value: por
            - name: PAPERLESS_TIME_ZONE
              value: America/Vancouver
            - name: PAPERLESS_REDIS
              value: redis://paperless-redis:6379
            - name: PAPERLESS_DBHOST
              value: paperless-postgres-rw
            - name: PAPERLESS_DBPORT
              value: "5432"
            - name: PAPERLESS_DBNAME
              value: paperless_ngx
            - name: PAPERLESS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-creds
                  key: username
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-creds
                  key: password
          volumeMounts:
            - name: data
              mountPath: /usr/src/paperless/data
            - name: media
              mountPath: /usr/src/paperless/media
            - name: export
              mountPath: /usr/src/paperless/export
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: media
          persistentVolumeClaim:
            claimName: paperless-media
        - name: export
          persistentVolumeClaim:
            claimName: paperless-export
