apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: whoops-postgres
  namespace: whoops
  # annotations:
  #   cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 3

  storage:
    size: 1Gi

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: "s3://kryoseu-whoops/postgres"
        serverName: "whoops-postgres"
        s3Credentials:
          accessKeyId:
            name: aws-creds-envs
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-creds-envs
            key: ACCESS_SECRET_KEY

  backup:
    barmanObjectStore:
      destinationPath: "s3://kryoseu-whoops/postgres"
      s3Credentials:
        accessKeyId:
          name: aws-creds-envs
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds-envs
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 7d

  bootstrap:
    recovery:
      source: clusterBackup
      database: whoop_data
      owner: whoops
      secret:
        name: whoops-creds

  # (optional) For development
  # managed:
  #   services:
  #     additional:
  #       - selectorType: ro
  #         serviceTemplate:
  #           metadata:
  #             name: "whoop-db"
  #           spec:
  #             type: LoadBalancer
