apiVersion: v1
kind: Service
metadata:
  name: whoops-dev
  namespace: whoops
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: whoops-postgres
    app.kubernetes.io/managed-by: cloudnative-pg
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: "17"
    cnpg.io/cluster: whoops-postgres
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    cnpg.io/cluster: whoops-postgres
    cnpg.io/instanceRole: replica
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
