apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: paperless-postgres
spec:
  immediate: true
  schedule: "0 0 7 * * *"
  backupOwnerReference: cluster
  cluster:
    name: paperless-postgres
