apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-creds
  namespace: paperless-ngx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-kv-store
    kind: ClusterSecretStore
  target:
    name: paperless-ngx-creds
  data:
    - secretKey: username
      remoteRef:
        key: paperless-ngx
        property: DB_USERNAME
    - secretKey: password
      remoteRef:
        key: paperless-ngx
        property: DB_PASSWORD
